name: Remove Past Deployments

on:
  deployment_status:
    types:
      - success

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Navigate to frontend directory
        run: cd frontend

      - name: Authenticate with GitHub
        uses: actions/github-script@v6
        with:
          script: |
            const deployments = await github.repos.listDeployments({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            for (const deployment of deployments.data) {
              if (deployment.id !== context.payload.deployment.id) {
                await github.repos.deleteDeployment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  deployment_id: deployment.id,
                });
                console.log(`Deleted deployment: ${deployment.id}`);
              }
            }
