name: Remove Past Deployments

on:
  deployment_status:
    types:
      - success

permissions:
  deployments: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with GitHub and Remove Past Deployments
        uses: actions/github-script@v6
        with:
          script: |
            const deployments = await github.repos.listDeployments({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            console.log(`Found ${deployments.data.length} deployments.`);

            for (const deployment of deployments.data) {
              if (deployment.id !== context.payload.deployment.id) {
                try {
                  console.log(`Marking deployment ${deployment.id} as inactive.`);
                  await github.repos.createDeploymentStatus({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    deployment_id: deployment.id,
                    state: "inactive",
                  });

                  console.log(`Deleting deployment: ${deployment.id}`);
                  await github.repos.deleteDeployment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    deployment_id: deployment.id,
                  });
                } catch (error) {
                  console.error(`Failed to delete deployment ${deployment.id}:`, error.message);
                }
              } else {
                console.log(`Skipping current deployment: ${deployment.id}`);
              }
            }
